#!/usr/bin/env sh

set -e

DEBUG_MODE=

if [ "$1" = "debug" ]; then
    DEBUG_MODE=debug
fi

cd ve.net.alge.cxcdobles.targetplatform
./plugin-builder $DEBUG_MODE ../ve.net.alge.cxcdobles ../ve.net.alge.cxcdobles.test
